#!/bin/bash

# This bash script obtains a copy of the [CuTest]() for local use.

mkdir -p archive/ansi-c/specs/cuTest

rm -rf archive/ansi-c/specs/cuTest/CuTest.h

rm -rf archive/ansi-c/specs/cuTest/CuTest.c

wget --directory-prefix=archive/ansi-c/specs/cuTest https://github.com/stephengaito/cutest/raw/combined/CuTest.h

wget --directory-prefix=archive/ansi-c/specs/cuTest https://github.com/stephengaito/cutest/raw/combined/CuTest.c

