#!/bin/bash

# This bash script obtains a copy of the [LunaTest]() for local use.

mkdir -p archive/lua/specs/lunaTest

rm -rf archive/lua/specs/lunaTest/lunatest.lua

wget --directory-prefix=archive/lua/specs/lunaTest https://github.com/stephengaito/lunatest/raw/master/lunatest.lua

mkdir -p textadept/specs/lunaTest

rm -rf textadept/specs/lunaTest/lunatest.lua

wget --directory-prefix=textadept/specs/lunaTest https://github.com/stephengaito/lunatest/raw/master/lunatest.lua

