#!/usr/bin/env racket
#lang racket

(define ignoreValue0 (system "reset"))

;; RUN TESTS 
;;
(require racket/rerequire)

(define (run-tests aPath)
  (begin
    (printf "\nRuning tests for [~a]\n" aPath) (flush-output)
    (dynamic-rerequire aPath)
  )
)

(define (rackunit-modules)
  (for ([ aPath (in-directory "specs")])
    (when (regexp-match (regexp ".*Spec.rkt$") aPath)
      (run-tests aPath)
    )
  )
)

(define ignoreValues (rackunit-modules))

;; CHECK DOCUMENTATION using doc-coverage
;;

(require racket/path)
(require doc-coverage)

(define (scribble-modules)
  (remove*
    (map string->path (list "info.rkt" "main.rkt"))
    (filter 
      (lambda (aPath) (equal? (filename-extension aPath) #"rkt"))
      (directory-list)
    )
  )
)

(define (check-module-documentation aModule)
  (let ([ moduleName 
          (string->symbol
            (string-append "diSimpInterpreter/" 
              (path->string (path-replace-suffix aModule ""))
            )
          )
       ])
    (begin 
      (printf "\nChecking documentation for [~a]\n" moduleName) (flush-output)
      (dynamic-rerequire moduleName)
      (check-all-documented moduleName)
    )
  )
)

(define ingoreValues2 (map check-module-documentation (scribble-modules)))

