#!/bin/bash

# This bash script sets up the LambdaPi4Racket packages

reset 

echo ""
echo "installing [doc-coverage] for use in the tests"
echo ""
raco pkg install doc-coverage

echo ""
echo "linking [lp4RacketLayer]"
echo ""
raco pkg install --link pkgs/lp4RacketLayer

echo ""
echo "linking [STLCAlg]"
echo ""
raco pkg install --link pkgs/STLCAlg

echo ""
echo "seting up [lp4RacketLayer]"
echo ""
raco setup lp4RacketLayer

echo ""
echo "seting up [STLCAlg]"
echo ""
raco setup STLCAlg

