#!/bin/sh
#
# Post-{commit, checkout, merge} hook to set version infomation

git log -1 --date=short \
  --pretty=format:"
typedef struct keyValueStruct {
  const char *key;
  const char *value;
} KeyValues;

static const KeyValues gitKeyValues[] = {
  { \"authorName\",      \"%an\"},
  { \"commitDate\",      \"%ad\"},
  { \"commitShortHash\", \"%h\"},
  { \"commitLongHash\",  \"%H\"},
  { \"subject\",         \"%s\"},
  { \"notes\",           \"%N\"},
  { NULL,                NULL}
};
" HEAD > archive/ansi-c/lib/gitVersion.h

git log -1 --date=short \
  --pretty=format:"
return {
  authorName      = \"%an\",
  commitDate      = \"%ad\",
  commitShortHash = \"%h\",
  commitLongHash  = \"%H\",
  subject         = \"%s\",
  notes           = \"%N\"
}
" HEAD > archive/lua/lib/gitVersion.lua
