#!/bin/bash

# This bash script sets up the Racket DiSimp package

reset

echo ""
echo "installing [doc-coverage] for use in tests" 
echo ""
raco pkg install doc-coverage   # used for the tests

echo ""
echo "linking [diSimpRacketLayer]"
echo ""
raco pkg install --link pkgs/diSimpRacketLayer

echo ""
echo "linking [diSimp]"
echo ""
raco pkg install --link pkgs/diSimp

echo ""
echo "setting up [diSimpRacketLayer]"
echo ""
raco setup diSimpRacketLayer

echo ""
echo "setting up [diSimp]"
echo ""
raco setup diSimp
