#!/bin/bash

reset

echo ""
echo "Setting up [racketLayer]"
echo ""

raco setup racketLayer
pushd pkgs/racketLayer > /dev/null
raco scribble +m --latex-section 1 --dest latex scribblings/racketLayer.scrbl
pushd latex > /dev/null
rm -rf manual-style.tex racket.tex scribble-load-replace.tex
rm -rf scribble-load.tex scribble.tex
popd > /dev/null
popd > /dev/null

echo ""
echo "Setting up [STLCAlg]"
echo ""

raco setup STLCAlg
pushd pkgs/STLCAlg > /dev/null
raco scribble +m --latex-section 1 --dest latex scribblings/STLCAlg.scrbl
pushd latex > /dev/null
rm -rf manual-style.tex racket.tex scribble-load-replace.tex
rm -rf scribble-load.tex scribble.tex
popd > /dev/null
popd > /dev/null

echo ""
echo "Copying documentation"
echo ""

mkdir -p doc
rsync -av pkgs/racketLayer/doc .
rsync -av pkgs/STLCAlg/doc .
rsync -av pkgs/combined/doc .
mkdir -p latex
rsync -av pkgs/racketLayer/latex .
rsync -av pkgs/STLCAlg/latex .
rsync -av pkgs/combined/latex .
echo ""
