#!/bin/bash

# This bash script sets up the Racket DiSimp package

diSimpDir=$HOME/.diSimp/racket

if [ -d $diSimpDir ]; then
  mkdir -p $diSimpDir/pkgs/diSimp/scribblings
  cp -r pkgs $diSimpDir
  raco pkg install --link $diSimpDir/pkgs/diSimp
else
  echo "Please setup the diSimplexLaTeX buildTool first"
fi

