sequenceDiagram
  participant m as joylol-main (globals)
  participant tf as testFactory (tests)
  participant ts as testStats (tests)
  participant tr as testRunner (globals)

  %% specify context switches
  activate m
  m -X tf : create (globals)
  m ->> tf : globals.runTestCase
  deactivate m
  activate tf
  tf -X ts : create (tests)
  tf -X tr : create (tests)
  tf ->> tr : tests.runTestCase
  deactivate tf
  activate tr
  loop assertions
    tr ->> ts : assert
    deactivate tr
   activate ts
    ts ->> tr : switch
   deactivate ts
   activate tr
    note over ts,tr :     ...
    tr ->> ts : assert
    deactivate tr
    activate ts
    ts ->> tr : switch
    deactivate ts
    activate tr
  end
  tr ->> ts : results
  deactivate tr
  activate ts
  ts ->> m : results
  deactivate ts
  activate m
  deactivate m

