#!/usr/bin/env racket
#lang racket

(require net/sendurl)

(require
  "./server/restfulServlets.rkt"
  "./server/dseFramework.rkt"
)
 
;; parse the command line
;;
(define main-page   (make-parameter "/"))
(define browser-cmd (make-parameter ""))
;;
(command-line
  #:program "diSimpExplorer"
  #:args browser-command
  (browser-cmd (string-join browser-command " " #:after-last " "))
)

;; determine which browser to use 
;;
(if (non-empty-string? (string-trim (browser-cmd)))
  (begin 
    (external-browser (cons (browser-cmd) ""))
    (display (string-join (list "using browser command: [" (browser-cmd) "]\n")))
  )
  (display "using the default browser\n")
)

;; Start the sever
;;
(run
  #:launch-browser? #t
  #:quit? #t
  #:port 0
  #:servlet-path (main-page)
)

