#!/usr/bin/env racket
#lang racket

(require 
  web-server/servlet
  web-server/servlet-env
)

(define (start req)
  (response/xexpr
    `(html 
       (head 
        (title "Hello world!")
      )
      (body 
        (p "Hey out there!")
        (p ,(path->string (current-directory)))
        (p ,(path->string (find-system-path 'home-dir)))
        (p ,(path->string (path->directory-path (path->complete-path (find-system-path 'run-file)))))
      )
    )
  )
)

(serve/servlet 
  start 
  #:port 0
  #:server-root-path (current-directory)
  #:servlets-root (current-directory)
  #:extra-files-paths (list "../javascript" (build-path default-web-root "htdocs"))
  #:launch-browser? true
)
