sequenceDiagram
  participant m as joylol-main (globals)
  participant tr as testsRunner  (testsRunner  tests globals)
  participant tm as testsMonitor (testsMonitor tests globals)

  %% specify context switches
  activate m
  m  ->> m : runTestSuite
  m  ->> m : defineNaming (testsRunner)
  m  ->> m : defineNaming (testsMonitor)
  m  -X tr : defineContext (testsRunner)
  m  -X tm : defineContext (testsMonitor)
  m  ->> tr : switchCtx
  deactivate m
  activate tr
  loop assertions
    tr ->> tr : startTestSuite
    tr ->> tr : runTestSuite
    tr ->> tm : reportSuiteResults
    deactivate tr
    activate tm
    tm ->> tm : recordSuiteResults
    tm ->> tr  : switchCtx
    deactivate tm
    activate tr
    tr ->> tr : stopTestSuite
    note over tr,tm :     ...
    tr ->> tr : startTestSuite
    tr ->> tr : runTestSuite
    tr ->> tm : reportSuiteResults
    deactivate tr
    activate tm
    tm ->> tm : recordCaseResults
    tm ->> tr  : switchCtx
    deactivate tm
    activate tr
    tr ->> tr : stopTestSuite
  end
  tr ->> tm : results
  deactivate tr
  activate tm
  tm ->> m : results
  deactivate tm
  activate m
  deactivate m

