sequenceDiagram
  participant m as joylol-main (globals)
  participant tr as testRunner (testRunner globals)
  participant tm as testMonitor (testMonitor tests globals)

  %% specify context switches
  activate m
  m  ->> m : runTestCase
  m  ->> m : defineNaming (testRunner)
  m  ->> m : defineNaming (testMonitor)
  m  -X tr : defineContext (testRunner)
  m  -X tm : defineContext (testMonitor)
  m  ->> tr : switch
  deactivate m
  activate tr
  loop assertions
    tr ->> tm : assert
    deactivate tr
    activate tm
    tm ->> tr : switch
    deactivate tm
    activate tr
    note over tr,tm :     ...
    tr ->> tm : assert
    deactivate tr
    activate tm
    tm ->> tr : switch
    deactivate tm
    activate tr
  end
  tr ->> tm : results
  deactivate tr
  activate tm
  tm ->> m : results
  deactivate tm
  activate m
  deactivate m

